#!/bin/bash

VALID_BRANCH_REGEX="^(master$|dev\/.+)"

if [[ ! $(git rev-parse --abbrev-ref HEAD) =~ $VALID_BRANCH_REGEX ]]
then
    echo "Branch names should follow this pattern: ${VALID_BRANCH_REGEX}."
    exit 1
fi

exit 0
