#!/bin/bash

main() {
	topdir="$(git rev-parse --show-toplevel)"
	self="${topdir}/ci"
	pyproject_toml_path="${topdir}/pyproject.toml"
	v2_dir="${topdir}/v2"
	v2_src="${v2_dir}/robotmk"
	v2_tests="${v2_dir}/tests"
	checkmk_extensions_dir="${topdir}/checkmk_extensions"
	mode="${1}"
	shift

	case "${mode}" in
	'black')
		poetry run black --config "${pyproject_toml_path}" "$@"
		;;

	'black-check-all')
		"${self}" black --check "${v2_src}" "${v2_tests}"
		;;

	'isort')
		poetry run isort --settings-path "${pyproject_toml_path}" "$@"
		;;

	'isort-check-all')
		"${self}" isort --check-only "${v2_src}" "${v2_tests}"
		;;

	'mypy')
		poetry run mypy --config-file "${pyproject_toml_path}" "$@"
		;;

	'mypy-check-all')
		"${self}" mypy "${v2_src}" "${v2_tests}"
		;;

	'pylint')
		poetry run pylint --rcfile "${pyproject_toml_path}" "$@"
		;;

	'pylint-check-all')
		"${self}" pylint --recursive true "${v2_src}" "${v2_tests}"
		;;

	'pytest')
		poetry run pytest --rootdir "${topdir}" "$@"
		;;

	'pytest-check-all')
		"${self}" pytest "${v2_tests}"
		;;

	'PSScriptAnalyzer-check-all')
		pwsh_output=$(pwsh -Command "Invoke-ScriptAnalyzer -Settings ${topdir}/PSScriptAnalyzerSettings.psd1 -Path ${checkmk_extensions_dir} -Recurse")
		pwsh_exitcode="$?"
		if [ "${pwsh_exitcode}" -eq 0 ]; then {
			if [ -z "${pwsh_output}" ]; then {
				echo "No static Powershell issues found"
				return 0
			} else {
				echo "${pwsh_output}"
				return 1
			}
			fi
		} else {
			echo "${pwsh_output}"
			return "${pwsh_exitcode}"
		}
		fi
		;;

	'check-all')
		exit_code=0
		for tool in black isort mypy pylint pytest PSScriptAnalyzer
		do
			"${self}" "${tool}-check-all"
			exit_code=$(( exit_code + $? ))
		done
		return "${exit_code}"
		;;

	*)
		echo "Unknown mode: ${mode}" 1>&2
		return 1
		;;
	esac

	return "$?"
}

main "$@"
exit "$?"
