#!/bin/bash

set -e

main() {
    topdir="$(git rev-parse --show-toplevel)"
    pipfile="${topdir}/Pipfile"
    mode="${1}"
    shift

    case "${mode}" in
        'lock')
            execute_pipenv_command "${pipfile}" lock --dev
            ;;

        'sync')
            execute_pipenv_command "${pipfile}" sync --dev
            ;;

        'run')
            execute_pipenv_command "${pipfile}" run "$@"
            ;;

        *)
            echo "Unknown mode: ${mode}" 1>&2
            return 1
            ;;
    esac

    return 0
}

execute_pipenv_command() {
    pipfile="${1}"
    shift
    PIPENV_PIPFILE="${pipfile}" PIPENV_VENV_IN_PROJECT=true PIPENV_NOSPIN=true pipenv "$@"
}

main "$@"
exit "$?"
