#!/bin/bash

set -e

TOPDIR="$(git rev-parse --show-toplevel)"
CHECKMK_DIR="${TOPDIR}/checkmk"
export PIPENV_PIPFILE="${TOPDIR}/Pipfile"
export PIPENV_VENV_IN_PROJECT=true
export PIPENV_NOSPIN=true

main() {
    mode="${1}"
    shift

    case "${mode}" in
        'lock')
            build_pipfile_from_template_and_additional_pipfile "${TOPDIR}/Pipfile_template" "${CHECKMK_DIR}/Pipfile" ./checkmk > "${TOPDIR}/Pipfile"
            pipenv lock --dev
            ;;

        'sync')
            pipenv sync --dev
            ;;

        'run')
            pipenv run "$@"
            ;;

        *)
            echo "Unknown mode: ${mode}" 1>&2
            return 1
            ;;
    esac

    return 0
}

build_pipfile_from_template_and_additional_pipfile() {
    ADDITONAL_PACKAGES=$(extract_packages_from_pipfile "${2}")
    ADDITONAL_PACKAGES=$(replace_relative_paths_in_pipfile_packages "${ADDITONAL_PACKAGES}" "${3}")
    build_pipfile_from_template_and_additional_packages "${1}" "${ADDITONAL_PACKAGES}"
}

extract_packages_from_pipfile() {
    awk '/\[packages\]/{flag=1;next}/^$/{flag=0}flag' "${1}"
}

replace_relative_paths_in_pipfile_packages() {
    echo "${1/path = \".\//path = \"${2}\/}"
}

build_pipfile_from_template_and_additional_packages() {
    awk -v additional_packages="${2}" '//; /\[packages\]/{print additional_packages}' "${1}"
}

main "$@"
exit "$?"
