#!/bin/bash

set -e

main() {
    setup_python_environment "${PYTHON_VERSION}"

    setup_powershell

    git config core.hooksPath .githooks
}

setup_python_environment() {
    check_poetry_executable
    export POETRY_VIRTUALENVS_IN_PROJECT=true
    poetry install --with dev
}

check_poetry_executable() {
    command -v poetry > /dev/null || {
        echo "poetry executable not found, aborting. Installing poetry is non-trivial, please do it manually."
        exit 1
    }
}

setup_powershell() {
    sudo apt-get install wget apt-transport-https software-properties-common
    wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
    sudo apt-get update
    sudo apt-get install powershell
    pwsh -Command "Install-Module -Name PSScriptAnalyzer"
}

main
