# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-11-22h2-enterprise"
  config.vm.box_version = "2202.0.2306"

  config.vm.provider "virtualbox" do |vb|
    vb.name = ENV.fetch("ROBOTMK_VAGRANT_NAME", "robotmk")
    vb.cpus = ENV.fetch("ROBOTMK_VAGRANT_CPUS", 4)
    vb.memory = ENV.fetch("ROBOTMK_VAGRANT_MEMORY", 4096)
    vb.gui = ENV.fetch("ROBOTMK_VAGRANT_GUI", "true") == "true"
    vb.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]  # drag-and-drop
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]  # bidirectional clipboard
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../", "/robotmk"

  config.vm.provision "shell", path: "scripts/provision.ps1"
  config.vm.provision "shell", path: "scripts/provision_poetry.ps1"
end
