channels:
  - conda-forge

dependencies:
  # packages listed here are fetched and installed from conda-forge. 
  - python=3.12            
  - pip=23.2.1  
  - pip:
    # packlages listed here are fetched from pypi.org and installed using pip.
    - robotframework==7.1.1
    - psutil
    - mergedeep

