ARG VARIANT
FROM checkmk/check-mk-enterprise:$VARIANT

# install python3 on the container
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \ 
    && apt-get -y install wget build-essential libreadline-gplv2-dev libncursesw5-dev \
    libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev \
    && cd /tmp && wget https://www.python.org/ftp/python/3.9.4/Python-3.9.4.tgz \
    && tar xzf Python-3.9.4.tgz  \
    && cd Python-3.9.4 \
    && ./configure \
    && make build_all \
    && make install

# install python modules to run the Robotmk plugin in this container 
RUN pip3 install robotframework pyyaml mergedeep python-dateutil ipdb 

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends jq tree htop vim git telnet file lsyncd
