name: CI

on: [push, pull_request]

jobs:
  static_and_unit:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
        - name: Python formatting
          step: black-check-all
        - name: Python import sorting
          step: isort-check-all
        - name: Python type checking
          step: mypy-check-all
        - name: Python linting
          step: pylint-check-all
        - name: Python unit tests
          step: pytest-check-all
        - name: Powershell static analysis
          step: PSScriptAnalyzer-check-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version-file: "pyproject.toml"
    
    - name: Setup Poetry
      run: python3 -m pip install poetry

    - name: Setup environment
      run: ./setup

    - name: ${{ matrix.name  }}
      env:
        STEP: ${{ matrix.step }}
      run: ./ci "${STEP}"

  check_success:
    if: always()

    needs:
    - static_and_unit

    runs-on: Ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
