name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - name: Rust formatting
          step: cargo-fmt-check
        - name: Rust linting
          step: cargo-clippy
        - name: Rust tests
          step: cargo-test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup environment
      run: ./setup

    - name: ${{ matrix.name  }}
      env:
        STEP: ${{ matrix.step }}
      run: ./ci "${STEP}"

  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
        - name: Rust formatting
          step: cargo-fmt-check
        - name: Rust linting
          step: cargo-clippy
        - name: Rust tests
          step: cargo-test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: "Setup Rust"
      uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
      with:
        components: rustfmt, clippy

  check_success:
    if: always()

    needs:
    - linux
    - windows

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
