name: CI

on: [push, pull_request]

jobs:
  static_and_unit:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
        - name: Formatting
          step: black-check-all
        - name: Import sorting
          step: isort-check-all
        - name: Type checking
          step: mypy-check-all
        - name: Linting
          step: pylint-check-all
        - name: Unit tests
          step: pytest-check-all

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Add Python version to environment
      run: cat python_version >> $GITHUB_ENV

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Environment
      run: |
        # librrd-dev: Needed for building rrdtool python bindings.
        # libldap2-dev: Needed for building python-ldap.
        # libsasl2-dev: Needed for building python-ldap.
        # libkrb5-dev: Needed for building pykerberos.
        sudo apt-get update
        sudo apt-get install librrd-dev libldap2-dev libsasl2-dev libkrb5-dev
        pip3 install pipenv
    
    - name: Cache virtual environment
      id: cache-venv
      uses: actions/cache@v3
      with:
        key: venv-${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}
        path: .venv
    
    - if: ${{ steps.cache-venv.outputs.cache-hit == false }}
      name: Build virtual environment if necessary
      run: ./pipenv sync

    - name: ${{ matrix.name  }}
      env:
        STEP: ${{ matrix.step }}
      run: ./ci "${STEP}"

  check_success:
    if: always()

    needs:
    - static_and_unit

    runs-on: Ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
