name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.type.os }}
    name: ${{ matrix.type.target }} (${{ matrix.type.os }})
    strategy:
      matrix:
        type:
          - { os: windows-latest, target: x86_64-pc-windows-gnu }
          - { os: ubuntu-latest,  target: x86_64-unknown-linux-gnu }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Setup Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          components: rustfmt, clippy
          target: ${{ matrix.type.target }}

      - run: cargo fmt -- --check
        working-directory: ${{ github.workspace }}/v2/robotmk/

      - run: cargo test --all-targets --target ${{ matrix.type.target }}
        working-directory: ${{ github.workspace }}/v2/robotmk/

      - run: cargo clippy --all-targets --target ${{ matrix.type.target }} -- --deny warnings
        working-directory: ${{ github.workspace }}/v2/robotmk/
