name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CMKRMK_PAT }}
        with:
          path-to-signatures: "version1/cla.json"
          path-to-document: "https://github.com/elabit/robotmk/blob/main/cla/cla.md" # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: "cla"
          allowlist: simonmeggle,SoloJacobs,racicLuka,jherbel,cmkrmk

          #below are the optional inputs - If the optional inputs are not given, then default values will be taken
          #remote-organization-name: enter the remote organization name where the signatures should be stored (Default is storing the signatures in the same repository)
          #remote-repository-name:  enter the  remote repository name where the signatures should be stored (Default is storing the signatures in the same repository)
          #create-file-commit-message: 'For example: Creating file for storing CLA Signatures'
          #signed-commit-message: 'For example: $contributorName has signed the CLA in #$pullRequestNo'
          custom-notsigned-prcomment: '<br/>Thank you for your Pull Request, we really appreciate it!<br/>We kindly ask that you to agree to our CLA (https://github.com/elabit/robotmk/blob/main/cla/cla.md) before we can accept your contribution.<br/>To accept/sign the CLA, copy the line between the two following lines ("I have read..."), and add the copied line as a new comment to the pull request. The CLA-bot will add you to the list of accepted contributors.<br/>'
          #custom-pr-sign-comment: 'The signature to be committed in order to sign the CLA'
          #custom-allsigned-prcomment: 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          #lock-pullrequest-aftermerge: false - if you don't want this bot to automatically lock the pull request after merging (default - true)
          #use-dco-flag: true - If you are using DCO instead of CLA
