name: Test

on:
  push:
    branches: 
      - 'v1/dev'


# dummy job
jobs:
  foo:
    name: testjob
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: test
        run: echo "foo"