---
name: "Micromamba"

on:
  workflow_call: {}

env:
  VERSION: "2.1.1-0"

jobs:
  download_and_cache:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir micromamba
      
      # Micromamba wants its own executable to be called micromamba or micromamba.exe and complains if this is not the case:
      # Error unknown MAMBA_EXE: "/tmp/not-micromamba", filename must be mamba or micromamba
      # /tmp/mambaf893b04kxn5: line 3: not-micromamba: command not found
      - run: curl --location --output micromamba/micromamba "https://github.com/mamba-org/micromamba-releases/releases/download/${{ env.VERSION }}/micromamba-linux-64"
      - run: curl --location --output micromamba/micromamba.exe "https://github.com/mamba-org/micromamba-releases/releases/download/${{ env.VERSION }}/micromamba-win-64.exe"
      
      - uses: actions/upload-artifact@v4
        with:
          name: micromamba
          path: micromamba/
          if-no-files-found: error
          overwrite: true
