name: Build MKPs

on:
  push:
    branches: 
      - 'v1/stable'
      # - 'v1/dev'

jobs:
  # ////////////////////////////////////////////////////////////////////////              
  build_cmk22:
    name: Build Robotmk MKP (CMK v2.2)
    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.2.0-daily
    steps:


      #  Uncomment this to debug
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3        

      - name: Install tools
        run: apt update && apt-get -y install sudo jq tree hub
      - name: Create Checkmk Site
        run: /docker-entrypoint.sh /bin/true
      - name: Checkout Robotmk repository
        uses: actions/checkout@v2
      - name: Link repository files into container
        run: .devcontainer/linkfiles.sh full
      - name: Update GITHUB_PATH
        run: echo "/omd/sites/cmk/bin" >> $GITHUB_PATH
      - name: Build MKP
        run: .devcontainer/build.sh
        id: cmkpkg
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{ steps.cmkpkg.outputs.artifactname }}
            path: ${{ steps.cmkpkg.outputs.pkgfile }}

  # ////////////////////////////////////////////////////////////////////////              
  # build_cmk23:
  #   name: Build Robotmk MKP (CMK v2.3)
  #   runs-on: ubuntu-latest
  #   container:
  #     image: checkmk/check-mk-raw:2.3.0-daily
  #   steps:

  #     - name: Install tools
  #       run: apt update && apt-get -y install sudo jq tree hub
  #     - name: Create Checkmk Site
  #       run: /docker-entrypoint.sh /bin/true
  #     - name: Checkout Robotmk repository
  #       uses: actions/checkout@v2
  #     - name: Link repository files into container
  #       run: .devcontainer/linkfiles.sh full
  #     - name: Update GITHUB_PATH
  #       run: echo "/omd/sites/cmk/bin" >> $GITHUB_PATH

  #     #  Uncomment this to debug
  #     - name: Setup tmate session
  #       uses: mxschmitt/action-tmate@v3            


  #     - name: Build MKP
  #       run: .devcontainer/build.sh
  #       id: cmkpkg
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #           name: ${{ steps.cmkpkg.outputs.artifactname }}
  #           path: ${{ steps.cmkpkg.outputs.pkgfile }}

  # ////////////////////////////////////////////////////////////////////////              
  build_cmk24:
    name: Build Robotmk MKP (CMK v2.4)
    runs-on: ubuntu-latest
    container:
      image: checkmk/check-mk-raw:2.4.0-daily
    steps:
      - name: Install tools
        run: apt update && apt-get -y install sudo jq tree hub
      - name: Create Checkmk Site
        run: /docker-entrypoint.sh /bin/true
      - name: Checkout Robotmk repository
        uses: actions/checkout@v2
      - name: Link repository files into container
        run: .devcontainer/linkfiles.sh full
      - name: Update GITHUB_PATH
        run: echo "/omd/sites/cmk/bin" >> $GITHUB_PATH

      #  Uncomment this to debug
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3            


      - name: Build MKP
        run: .devcontainer/build.sh
        id: cmkpkg
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{ steps.cmkpkg.outputs.artifactname }}
            path: ${{ steps.cmkpkg.outputs.pkgfile }}

  # ////////////////////////////////////////////////////////////////////////              
  release:
    name: Release Robotmk MKP for all CMK versions
    runs-on: ubuntu-latest
    needs:
       - build_cmk22
      #- build_cmk23
       - build_cmk24 
    steps:
      - name: Install tools
        run: sudo apt update && sudo apt-get -y install hub
      - name: Checkout Robotmk repository 
        uses: actions/checkout@v2     
      - name: Download CMK artifacts
        uses: actions/download-artifact@v4
        with:         
          pattern: "*.mkp"
          path: ./
          merge-multiple: true
      - name: Debug - Show downloaded content
        run:  |
          ls -la *.mkp          
          echo $(pwd)      
      - name: Download chag
        uses: wei/curl@master
        with:
          args: https://raw.githubusercontent.com/mtdowling/chag/master/chag --output chag
      - name: chag
        run: bash chag contents > RELEASE_CHANGELOG.md
      - name: Determine version tag
        id: version
        run: |
          git fetch --tags
          TAG=$(git describe --tags --exact-match)
          echo "TAG=$TAG"
          echo "version=$TAG" >> "$GITHUB_OUTPUT"
      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          bodyFile: RELEASE_CHANGELOG.md
          draft: false
          prerelease: false
          artifacts: "robotmk.1.5.1-cmk2.4.mkp"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true


      #  Uncomment this to debug
      #- name: Setup tmate session

      #  uses: mxschmitt/action-tmate@v3        

