---
name: "System tests"

on:
  workflow_call: {}

jobs:
  test_import_hololib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9
        with:
          target: x86_64-unknown-linux-gnu
          # By default, setup-rust-toolchain sets "-D warnings". As a side effect, the settings in
          # .cargo/config.toml are ignored:
          # https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags
          # "There are four mutually exclusive sources of extra flags"
          rustflags: ""
      - uses: actions/download-artifact@v4
        with:
          name: rcc
          path: /tmp/
      # file permissions are not retained during upload:
      # https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
      - run: chmod +x /tmp/linux64/rcc
      - run: echo "CARGO_MANIFEST_DIR=$(pwd)" >> $GITHUB_ENV
      - run: echo "TERMINATION_EXECUTABLE=$(cargo build --example termination --target=x86_64-unknown-linux-gnu --message-format=json | jq -r 'select(.reason == "compiler-artifact" and .target.kind[] == "example") | .executable')" >> $GITHUB_ENV
      - run: echo "RCC_EXECUTABLE=/tmp/linux64/rcc" >> $GITHUB_ENV
      - run: ./build.sh
      - run: sudo unshare --net -- "${CARGO_MANIFEST_DIR}/un.sh" "$CARGO_MANIFEST_DIR" "$RCC_EXECUTABLE" "$TERMINATION_EXECUTABLE"
